### ISSUE TITLE
Background colors don't work on HStack

### ISSUE THREAD

**Issue by haveamission** [gluestack/gluestack-ui-themed-native-base#5]
### Description

Background colors don't show up on HStack, or many other elements

### Steps to reproduce

Use the component for [gluestack-ui-themed-native-base](https://github.com/gluestack/gluestack-ui-themed-native-base)

### gluestack-ui Version

1.0.8

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [X] Next

**Comment by akash3gtm** [comment]
hi @haveamission 
can you check now after updating to the latest version?
